server:
  port: 8072

spring:
  application:
    name: poi-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/introcom_pois
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8069/eureka/
